# -*- sh -*-

typeset -U path
path=(
      /bin(N-/)
      $HOME/local/bin(N-/)
      /opt/local/bin(N-/)
      /usr/local/bin(N-/)
      /usr/bin(N-/))

# sudo時のパスの設定
typeset -xT SUDO_PATH sudo_path
## 重複したパスを登録しない。
typeset -U sudo_path
sudo_path=({,/usr/local,/usr}/sbin(N-/))

# man用パスの設定
typeset -U manpath
manpath=(# 自分用
         $HOME/local/share/man(N-/)
         /opt/local/share/man(N-/)
         /usr/local/share/man(N-/)
         /usr/share/man(N-/))
